---
title: "Course Schedule"
---

# Lectures

The course will be held in two weekly lectures, starting **14.10.2024**. The lectures will be held in the Large Lecture Hall (GHS) at the Linnéstr. 5. The course will be held in English.

::: {.callout-note}
## Lecture Times
- Monday 11:15 am – 12:45 pm GHS
- Thursday 11:15 am – 12:45 pm GHS
:::

The course and the material are available online on this website. You may come back to study whenever it is suitable for you. Please note that the lectures are a place to give feedback on your understanding he topics. No feedback means all is good.

# Seminars

Seminars are an essential part of the course. They help you to understand the material better and to prepare for the final exam. Our experience shows that students who regularly work on the assignments have a better understanding of the material and are more successful in the final exam.


::: {.callout-warning}
## Seminar Start
**The seminars will start on October 22**
**The solutions to the exercise sheets have to be handed in on Thursdays before the lecture.**
:::

::: {.callout-note}
## Seminar Times
- Tuesday 11:15 am – 12:45 pm, SR 224
- Tuesday 15:15 am – 16:45 pm, ThHS
:::

The seminar will be held by Diptabrata Paul and Markus Anton.
